### ISSUE TITLE
Add additional ttlib::cstr methods to ttlib::sview

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/ttLib#246]
### Description:

Because ttlib::sview isn't zero-terminated, it can can include several of the ttlib::cstr functions that are not possible with ttlib::cview.

- Trim functions (Trimming a string_view simply entails removing prefix and/or suffix)
- ExtractSubString (this would return a view rather than a position)
- AssignSubString (this would return a view rather than a position)
- erase_from

**Comment by Randalphwa** [comment]
ExtractSubString() and AssignSubString() require passing in a string_view which we can't do with sview.
