### ISSUE TITLE
ttCFileDlg::SetInitialDir does not work as expected

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/ttLib#64]
### Description:
In **MakeSrcFiles**, the **CDlgSrcOptions** retrieves the current directory and calls **SetInitialDir**, but  **GetOpenFileName** still uses the last used directory location. In **CConvertDlg**, **UseCurrentDirectory** is called instead, and this works as expected -- the current directory is used in **GetOpenFileName**. There's some subtle differences between the two calls—in the case of **CDlgSrcOptions**, a trailing backslash is added to the end of the CWD. **UseCurrentDirectory** doesn't use a trailing backslash, but also sets the **m_cszCurDir**.

If the backslash is the issue, then **SetInitialDir** needs to be changed to remove it. If not setting **m_cszCurDir** is the issue, then it needs to be set.

### Issue Type:
- [x] Bug report
- [ ] Feature request
- [ ] Other

**Comment by Randalphwa** [comment]
The entire class has been replaced with ttlib::openfile which inherits from OPENFILENAME and sets the initial directory member of that structure.
